#!/bin/bash  
# chkconfig: - 85 15
# description: Tomcat for @appname@ Start Stop Restart  
# processname: @appname@

CATALINA_HOME=/usr/local/@appname@

case $1 in  
start)
STAT=`netstat -na |grep @http.port@| awk '{print $6}'`
if [ "$STAT" = "LISTEN" ]; then
	echo "@http.port@ PORT IS LISTENING, PLEASE STOP FIRST."
else
	su -c $CATALINA_HOME/bin/startup.sh tomcat
fi	
;;   
stop)
sh $CATALINA_HOME/bin/myshutdown.sh $2 
;;   
restart)  
sh $CATALINA_HOME/bin/myshutdown.sh  
su -c $CATALINA_HOME/bin/startup.sh tomcat
;;   
esac      
exit $?
